version: "3.9"

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports: 
        - "5672:5672"
        - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "panda"
    redis:
        container_name: redis
        image: redis:7.4.0-alpine
        ports:
        - "6379:6379"